apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynodejsapp-deployment
spec:
  selector:
    matchLabels:
      app: mynodejsapp
  template:
    metadata:
      labels:
        app: mynodejsapp
    spec:
      containers:
      - name: mynodejsapp
        image: gcr.io/veer-dil1/mynodejsapp
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
