apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: mynodejsapp
    context: .
    sync:
      infer: 
      - '**/*.js'  
deploy:
  kubectl:
    manifests:
      - k8s-manifests/deployment.yaml
      - k8s-manifests/service.yaml